# КОНФИГ МОДУЛЕЙ "Wendy"

# Здесь указаны модули по умолчанию, Вы можете их удалить или заменить своими
# Слова-исключения вы можете сами указать или изменить в Dictionary.conf (modules)

# ----------------------------------------------------------------------------------------------------------------
создатель = creator.py
# ----------------------------------------------------------------------------------------------------------------
обнови систему = Upgrade.py
обнови системы = Upgrade.py
обновить систему = Upgrade.py
обновить системы = Upgrade.py
обновление системы = Upgrade.py
обнови систем = Upgrade.py
# ----------------------------------------------------------------------------------------------------------------
стандартный протокол = work.py
стандартного протокола = work.py
# ----------------------------------------------------------------------------------------------------------------
умный чат = AI_Chat.py
умные чат = AI_Chat.py
умной чат = AI_Chat.py
умны чат = AI_Chat.py
умной чат = AI_Chat.py
чат = AI_Chat.py
# ----------------------------------------------------------------------------------------------------------------
чистка = clear.sh
# ----------------------------------------------------------------------------------------------------------------

# только для GNOME (использует gsettings)
# ----------------------------------------------------------------------------------------------------------------
включи ночной свет = NightLightON.py
ночной свет = NightLightON.py
ночную свет = NightLightON.py
# ----------------------------------------------------------------------------------------------------------------
выключи ночной свет = NightLightOFF.py
# ----------------------------------------------------------------------------------------------------------------
