# КОНФИГ МОДУЛЕЙ "Wendy"

# Здесь указаны модули по умолчанию, Вы можете их удалить или заменить своими
# Слова-исключения вы можете сами указать или изменить в Dictionary.conf (delete)

# Из-за использования малой модели Vosk могут быть некоторые неточности. 
# Поэтому слова могут быть записаны немного странно.
# Слова записаны с учетом: 1) Универсальности, 2) Склонений русского языка, 3) Возможности ошибки модели Vosk.
# Также стоит понимать, что Vosk воспринимает только русский язык. 
# Если вы захотите добавить английское слово, модель может обрабатывать его некорректно.
# Пример: "VScode" будет распознано как "в с кот".


# ----------------------------------------------------------------------------------------------------------------
создатель = creator.py
# ----------------------------------------------------------------------------------------------------------------
обнови систему = Upgrade.py
обнови системы = Upgrade.py
обновить систему = Upgrade.py
обновить системы = Upgrade.py
обновление системы = Upgrade.py
обнови систем = Upgrade.py
# ----------------------------------------------------------------------------------------------------------------
стандартный протокол = work.py
стандартного протокола = work.py
# ----------------------------------------------------------------------------------------------------------------
умный чат = AI_Chat.py
умные чат = AI_Chat.py
умной чат = AI_Chat.py
умны чат = AI_Chat.py
умной чат = AI_Chat.py
умный чад = AI_Chat.py
умны чад = AI_Chat.py
чат = AI_Chat.py
чад = AI_Chat.py
# ----------------------------------------------------------------------------------------------------------------
чистка = clear.sh
# ----------------------------------------------------------------------------------------------------------------

# только для GNOME (использует gsettings)
# ----------------------------------------------------------------------------------------------------------------
включи ночной свет = NightLightON.py
ночной свет = NightLightON.py
ночную свет = NightLightON.py
# ----------------------------------------------------------------------------------------------------------------
выключи ночной свет = NightLightOFF.py
выключи ночное свет = NightLightOFF.py
# ----------------------------------------------------------------------------------------------------------------
