# КОНФИГ ЗАПУСКАЕМЫХ ПРОГРАММ "Wendy"
# Замените название запускаемой программы при желании


# БРАУЗЕР ---------------------------------------------------------------------------------------------------------
browser =chromium
# -----------------------------------------------------------------------------------------------------------------

# ПРОВОДНИК -------------------------------------------------------------------------------------------------------
conductor =nautilus
# -----------------------------------------------------------------------------------------------------------------

# ТЕРМИНАЛ --------------------------------------------------------------------------------------------------------
terminal =gnome-terminal
# -----------------------------------------------------------------------------------------------------------------

# МАГАЗИН ПРИЛОЖЕНИЙ ----------------------------------------------------------------------------------------------
store =pamac-manager
# -----------------------------------------------------------------------------------------------------------------

# ОФИС ------------------------------------------------------------------------------------------------------------
office =libreoffice
# -----------------------------------------------------------------------------------------------------------------

# МЕССАНДЖЕР ------------------------------------------------------------------------------------------------------
messenger =Telegram
# -----------------------------------------------------------------------------------------------------------------

# СОЦ.СЕТЬ --------------------------------------------------------------------------------------------------------
socialnetwork =Telegram
# -----------------------------------------------------------------------------------------------------------------

# ЗАМЕТКИ ---------------------------------------------------------------------------------------------------------
notes =md.obsidian.Obsidian
# -----------------------------------------------------------------------------------------------------------------

# РЕДАКТОР КОДА ---------------------------------------------------------------------------------------------------
codeeditor =code
# -----------------------------------------------------------------------------------------------------------------


# Поиск происходит в том браузере, который указан у вас в "browser"

# ПОИСКОВАЯ СИСТЕМА -----------------------------------------------------------------------------------------------
websearch =https://duckduckgo.com/?q=

# https://duckduckgo.com/?q= DuckDuckGO
# https://www.google.ru/search?q= Google
# https://ya.ru/search/?text= Yandex
# -----------------------------------------------------------------------------------------------------------------

# ВИДЕО СИСТЕМА ---------------------------------------------------------------------------------------------------
videosearch = https://www.youtube.com/results?search_query=

# https://www.youtube.com/results?search_query= YouTube
# -----------------------------------------------------------------------------------------------------------------
