# КОНФИГ ЗАПУСКАЕМЫХ ПРОГРАММ "Wendy"
# Замените название запускаемой программы при желании


# Браузер
browser=chromium

# Проводник
conductor=nautilus

# Терминал
terminal=gnome-terminal

# Магазин приложений
store=pamac-manager

# Офис
office=libreoffice

# Мессанджер
messenger=Telegram

# Соц.сеть
socialnetwork=Telegram

# Заметки
notes=md.obsidian.Obsidian

# Редактор кода
codeeditor=code

# Поисковая система и видео система
# Поиск происходит в том браузере, который указан у вас в "browser"

websearch=https://duckduckgo.com/?q=

# https://duckduckgo.com/?q= DuckDuckGO
# https://www.google.ru/search?q= Google
# https://ya.ru/search/?text= Yandex

videosearch=https://www.youtube.com/results?search_query=

# https://www.youtube.com/results?search_query= YouTube

