# КОНФИГ ОСНОВНОГО СЛОВАРЯ "Wendy"

# Из-за использования малой модели Vosk могут быть некоторые неточности. 
# Поэтому слова могут быть записаны немного странно, особенно в разделе ПОЛУИЗМЕНЯЕМЫЕ (которые уже есть).
# Слова записаны с учетом условий: 1) Универсальности, 2) Склонений русского языка, 3) Возможности ошибки модели Vosk.
# Также стоит понимать, что Vosk воспринимает только русский язык. Если вы захотите добавить английское слово, модель может обрабатывать его некорректно.
# Пример: "VScode" будет распознано как "в с кот".


# ПОЛНОСТЬЮ ИЗМЕНЯЕМЫЕ
# Вы можете полностью переписать слова-активаторы для этих функций.

hello=здравствуй, ты тут, привет
browser=браузер, браузера, интернет
conductor=проводник
terminal=терминал
store=магазин, стор
office=офис
messenger=мессенджер, телега, телеграмм
socialnetwork=соц сеть, социальная сеть
notes=обсидиан, заметки
codeeditor=редактор кода, код
reboot=перезапуск, перезапусти компьютер
shutdown=выключение, выключение компьютера, выключи компьютер, выключить компьютер, занавес, выключения
sleep=спящий режим, спать, антракт

# Для modules слова не являются обязательными и преднозначены только для вашего удобства и удаления. 
# Для активации модуля достаточно сказать "венди + название модуля"
modules=запусти, начни, выполнение, выполнения, начинаем


# ПОЛУИЗМЕНЯЕМЫЕ
# Эти функции уже имеют слова-активаторы, но вы можете добавить свои слова-активаторы.

volume=
# Уже имеются:
# "увеличь громкость", "уменьши громкость", 
# "увеличить громкость", "уменьшить громкость", 
# "громкость больше", "громкость меньше", 
# "звук больше", "звук меньше", 
# "включи звук", "выключи звук", 
# "громкость на", "громкость мне", "громкость"
# ПРИМЕЧАНИЕ! Уменьшение/увеличение/выключение/включение/конкретная настройка звука пишется в одном месте.

websearch=
# Уже имеются:
# "найди", "найди в интернете", "найти", "найти в интернете", "ищи", "что такое",
# "когда", "в каком году", "где", "кто такой", "кто", "кто такая"

youtubesearch=
# Уже имеются:
# "найди на ютубе", "ищи на ютубе", "найти на ютубе",
# "найди на ютуб", "ищи на ютуб", "найти на ютуб",
# "найди на ютюбе", "ищи на ютюбе", "найти на ютюбе",
# "найди на ютюб", "ищи на ютюб", "найти на ютюб",
# "найди в ютубе", "ищи в ютубе", "найти в ютубе",
# "найди в ютуб", "ищи в ютуб", "найти в ютуб",
# "найди в ютюбе", "ищи в ютюбе", "найти в ютюбе",
# "найди в ютюб", "ищи в ютюб", "найти в ютюб"
