# КОНФИГ МОДУЛЕЙ "Wendy"

# Здесь указаны модули по умолчанию, Вы можете их удалить или заменить своими
# Поддерживаемые языки: C/C++, Java, Rust, GO, JS + node/deno, Python + venv, Ruby, Lua, Bash

# Помимо этих языков Wendy поддерживает запуск исполняемых файлов, тоесть, если нет вашего языка, вы все равно можете написать на нём модуль, откомпилировать и пользоваться.

# Так же поддерживается запуск любого языка, где расширение файла совпадает с названием интерпретатора, тоесть запуск модуля из терминала выглядит, на примере Lua, следующим образом: lua main.lua

# Слова-исключения вы можете сами указать или изменить в Dictionary.conf (modules)

создатель=creator.cpp
обнови систему=Upgrade.py
обнови системы=Upgrade.py
обновить систему=Upgrade.py
обновить системы=Upgrade.py
обновление системы=Upgrade.py
стандартный протокол=work.py
стандартного протокола=work.py
умный чат=AI_Chat.py
умные чат=AI_Chat.py
умной чат=AI_Chat.py

# только для GNOME (использует gsettings)
включи ночной свет=NightLightON.py
выключи ночной свет=NightLightOFF.py
ночной свет=NightLightON.py
ночную свет=NightLightON.py

