# ИСТОРИЯ КОМАНД "Wendy"

# Здесь будут записываться все обращения к Wendy, это нужно для контроля работоспособности программы
# Это информация никуда отправляться не будет!

# ВАШИ КОМАНДЫ ---------------------------------------------------------------------------------------------------


вэнди звук больше
вэнди громкость меньше
вэнди выключи компьютер
вэнди браузер
вэнди закройся
вэнди браузер
венди браузер
венди браузер
вэнди браузер
вэнди ночной свет
вэнди выключи ночная свет
вэнди выключи ночной свет
венди
ночной свет
вэнди выключи ночной свет
вэнди короче найди в интернете кто такой достоевский
вэнди короче пожалуйста найди кто такой достоевский ладно
вэнди найди на ютюбе кто такой достоевский
вэнди громкость на шестьдесят
венди громкость тише
