# ИСТОРИЯ КОМАНД "Wendy"

# Здесь будут записываться все обращения к Wendy, это нужно для контроля работоспособности программы
# Это информация никуда отправляться не будет!

# ВАШИ КОМАНДЫ ---------------------------------------------------------------------------------------------------

вэнди включи ночной свет
венди выключи ночной свет
вэнди включи ночной свет
вэнди выключи ночной свет
вэнди
я здесь обнови систему
вэнди
здравствуйте обнови систему
вэнди
здравствуйте обнови систему
вэнди
да здесь обнови систему
вэнди обнови систему
вэнди закройся
вэнди выключи компьютер
