#КОНФИГ для ОКНА WENDY (на данный момент функционал вырезан)
# - Пожалуйста, не изменяйте в будущей этот конфиг, потому что от него будет зависеть работоспособность и внешний вид окна


theme=dark
language=ru